version: '3.9'
services:
  postgres:
    image: postgres:14.1
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: student
